### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by matt40k** [SIMSBulkImport/SIMSBulkImport#10]
Application crash when loading file

System.InvalidOperationException: An ItemsControl is inconsistent with its items source.
  See the inner exception for more information. ---> System.Exception: Information for developers (use Text Visualizer to read this):
This exception was thrown because the generator for control 'System.Windows.Controls.DataGrid Items.Count:35' with name 'dataGrid' has received sequence of CollectionChanged events that do not agree with the current state of the Items collection.  The following differences were detected:
  Accumulated count 34 is different from actual count 35.  [Accumulated count is (Count at last Reset + #Adds - #Removes since last Reset).]

**Comment by matt40k** [comment]
Trace:: Matt40k.SIMSBulkImport.ConfigMan.GetDefaultEmailNotes(GET)

**Comment by matt40k** [comment]
Error doesn't occur when importing Excel file. Only CSV.

**Comment by rpwillis** [comment]
Issue is only when running under .net 4.5. This introduces changes to how background threads can access the UI controls. This should be able to be resolved using EnableCollectionSynchronization, but I can't get that to work.
http://stackoverflow.com/questions/14336750/upgrading-to-net-4-5-an-itemscontrol-is-inconsistent-with-its-items-source/16367902

Only way I can get it to work is by commenting out the 
            //dataGrid.Items.Refresh();
line in bw_ProgressChanged, but then the datagrid does update until the end.
