### ISSUE TITLE
Feature Request - Applicants

### ISSUE THREAD

**Issue by GeeDee86** [SIMSBulkImport/SIMSBulkImport#13]
Would it be possible to add support for "Applications" please?

i.e. we have 180 year 6 pupils moving to year 7 and joining us this year, and we want to be able to pre-load UDF Username and Work Email fields.

Ta :)

**Comment by rpwillis** [comment]
I've not looked at the feasibility of it in general, but I can say that I wouldn't have time before September to even look at it.

It would involve a whole lot of work to add the new 'user' type before even getting onto the UDF bit.

I don't know how much time Matt has.

**Comment by matt40k** [comment]
Have you tried imported as pupils then changing the filter to <any> @GeeDee86 ?

**Comment by matt40k** [comment]
Should be able to do this with the date effective in 2.4
