### ISSUE TITLE
Doesn't import boolean UDFs

### ISSUE THREAD

**Issue by matt40k** [SIMSBulkImport/SIMSBulkImport#9]
Doesn't import Boolean UDFs, no error displayed

Reported by @MicrodigitUK via EduGeek

**Comment by matt40k** [comment]
Replicated

**Comment by rpwillis** [comment]
I'll sort that out.

**Comment by matt40k** [comment]
Thanks! I've assigned it to you, he was trying it for pupils. I've added it SetPupilUDF (bool), however it looks like it needs to be converted to BoolAttribute or something - /API/blob/master/SIMSAPI/Classes/Pupil.cs
Could be totally wrong however!!

Also 1, 0 don't appear to convert to Boolean automatically like true\false.

**Comment by rpwillis** [comment]
Yes, the different attribute types are strongly typed, we’ve got that covered in Salamander AD so shouldn’t take long to code once I remember how to build the project again!.

**Comment by matt40k** [comment]
I've added the API stuff as a submodule, so when you pull it down it should just work, assume you still have the environment setting set for the SIMS apps directory

**Comment by matt40k** [comment]
Resolved in 6116128f9d6aa4420a26db27e7ec3d3a1b6572c7
